



from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 487)
        MainWindow.setStyleSheet("border-color: rgb(0, 170, 0);\n"
"gridline-color: rgb(255, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ekran = QtWidgets.QLabel(self.centralwidget)
        self.ekran.setGeometry(QtCore.QRect(20, 22, 681, 80))
        font = QtGui.QFont()
        font.setFamily("Nexa Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ekran.setFont(font)
        self.ekran.setStyleSheet("background-color: rgb(184, 175, 180);\n"
"color: rgb(0, 0, 255);")
        self.ekran.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ekran.setLineWidth(3)
        self.ekran.setMidLineWidth(2)
        self.ekran.setObjectName("ekran")
        self.Button0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button0.setGeometry(QtCore.QRect(10, 360, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button0.setFont(font)
        self.Button0.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button0.setObjectName("Button0")
        self.Button_ymnoch = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ymnoch.setGeometry(QtCore.QRect(180, 360, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ymnoch.setFont(font)
        self.Button_ymnoch.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button_ymnoch.setObjectName("Button_ymnoch")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(350, 280, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button3.setObjectName("Button3")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(180, 280, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button2.setObjectName("Button2")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(10, 280, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button1.setObjectName("Button1")
        self.Button_delim = QtWidgets.QPushButton(self.centralwidget)
        self.Button_delim.setGeometry(QtCore.QRect(350, 360, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button_delim.setFont(font)
        self.Button_delim.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button_delim.setObjectName("Button_delim")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(180, 200, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button5.setFont(font)
        self.Button5.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button5.setObjectName("Button5")
        self.Button9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button9.setGeometry(QtCore.QRect(350, 120, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button9.setFont(font)
        self.Button9.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button9.setObjectName("Button9")
        self.Button7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button7.setGeometry(QtCore.QRect(10, 120, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button7.setFont(font)
        self.Button7.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button7.setObjectName("Button7")
        self.Button8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button8.setGeometry(QtCore.QRect(180, 120, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button8.setFont(font)
        self.Button8.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button8.setObjectName("Button8")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(10, 200, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button4.setFont(font)
        self.Button4.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button4.setObjectName("Button4")
        self.Button6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button6.setGeometry(QtCore.QRect(350, 200, 165, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button6.setFont(font)
        self.Button6.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button6.setObjectName("Button6")
        self.Button_ravno = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ravno.setGeometry(QtCore.QRect(520, 310, 191, 131))
        self.Button_ravno.setMaximumSize(QtCore.QSize(16777199, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button_ravno.setFont(font)
        self.Button_ravno.setStyleSheet("background-color: rgb(0, 124, 0);")
        self.Button_ravno.setObjectName("Button_ravno")
        self.Button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.Button_plus.setGeometry(QtCore.QRect(520, 120, 191, 81))
        self.Button_plus.setMaximumSize(QtCore.QSize(16777199, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button_plus.setFont(font)
        self.Button_plus.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button_plus.setObjectName("Button_plus")
        self.Button_minys = QtWidgets.QPushButton(self.centralwidget)
        self.Button_minys.setGeometry(QtCore.QRect(520, 210, 191, 81))
        self.Button_minys.setMaximumSize(QtCore.QSize(16777199, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Button_minys.setFont(font)
        self.Button_minys.setStyleSheet("background-color: rgb(255, 73, 28);\n"
"border-color: rgb(0, 0, 127);")
        self.Button_minys.setObjectName("Button_minys")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 460, 641, 20))
        font = QtGui.QFont()
        font.setFamily("Whirl Cyrillic")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 72, 0);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "КАЛЬКУЛЯТОР ЧУНИНВ.Е. ТЮМЕНЬ"))
        self.ekran.setText(_translate("MainWindow", "Результат"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.Button_ymnoch.setText(_translate("MainWindow", "*"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button_delim.setText(_translate("MainWindow", "/"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button_ravno.setText(_translate("MainWindow", "="))
        self.Button_plus.setText(_translate("MainWindow", "+"))
        self.Button_minys.setText(_translate("MainWindow", "-"))
        self.label.setText(_translate("MainWindow", "Мой калькулятор нанисанный на Питоне Чунин В Е"))
